version: "3.9"

services:

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - main
    ports:
      - "5433:5432"
    restart: on-failure


  redis:
    image: redis
    restart: on-failure
    hostname: redis
    ports:
      - '6380:6379'
    networks:
      - main

  webapp:
    restart: always
    build:
      context: ./app
    ports:
      - "8000:8000"
    command: [ "python3", "./manage.py", "runserver", "0.0.0.0:8000" ]
    links:
      - redis
      - postgres
    depends_on:
      - postgres
      - redis

    networks:
      - main

  worker:

    restart: always
    build: ./app
    command: [ 'celery', '-A', './config', 'worker', '-l', 'INFO' ]
    container_name: celery
    depends_on:
      - webapp
      - redis
      - postgres

  celery_beat:
    build: ./app
    hostname: celery_beat
    container_name: celery_beat
    restart: on-failure
    command: [ 'celery', '--workdir=./config', '-A', 'config', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler' ]
    links:
      - worker
      - redis
      - postgres
    depends_on:
      - worker
      - redis
    networks:
      - main



networks:
  main:

