version: '3.8'

volumes:
  app:
  worker:
  celery-beat:

networks:
  main:

services:
  postgres:
    image: postgres:14.6-alpine
    ports:
      - '127.0.0.1:5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - main

  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
    restart: always
    networks:
      - main

  app:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    command:
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '127.0.0.1:8000:8000'
    depends_on:
      - postgres
    networks:
      - main

  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    command: [ 'celery',  '-A', 'config', 'worker', '-l' ,'INFO']
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - postgres
      - app
      - redis
    networks:
      - main

  celery-beats:
    restart: always
    build:
      context: .
    volumes:
      - ./:/app
    command: [ 'celery', '-A', 'config', 'beat', '-l', 'INFO']
    links:
      - worker
      - redis
    depends_on:
      - postgres
      - app
      - redis
      - worker
    networks:
      - main
